### ISSUE TITLE
Error building Eudico on Mac M1

### ISSUE THREAD

**Issue by CluEleSsUK** [consensus-shipyard/ipc-agent#183]
While running the [quickstart guide](https://github.com/consensus-shipyard/ipc-agent/blob/main/docs/quickstart.md), I'm getting the following error when running: 
`make build && make install-infra` at the step
` [lotus-builder 7/7] RUN make spacenet:`

```
#15 57.53 # github.com/filecoin-project/lotus/cmd/eudico
#15 57.53 /usr/local/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
#15 57.53 /usr/bin/ld: /opt/filecoin/extern/filecoin-ffi/libfilcrypto.a(filcrypto-b101665716a8d1f4.filcrypto.4b299269-cgu.10.rcgu.o): Relocations in generic ELF (EM: 62)
```
The last line repeats a hundred or so times.

I appreciate the quickstart guide is targeted at Ubuntu, so feel free to close this if Mac M1 isn't in scope, but I'd love to get it running to try and build a subnet!
I see there is also a repo for eudico itself, so let me know if I should raise the issue there instead of there.

**Comment by dnkolegov** [comment]
Hey @CluEleSsUK.

Try this
```
docker build -t eudico --build-arg FFI_BUILD_FROM_SOURCE=1 .
```
instead of this
``` 
docker build -t eudico .
``` 
in `install_infra.sh`.

Or wait for the [fix](https://github.com/consensus-shipyard/ipc-agent/pull/193).

Thank you for reporting this bug.

**Comment by adlrocha** [comment]
This has been fixed in the infra scripts, unless there's any outstanding issue closing it for now. Thank you both
