### ISSUE TITLE
Cross-msgs: Integrate IPLD Resolver and IPC BitswapStore

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/ipc-agent#96]
The IPLD resolver is implemented as a general protocol that can be leveraged by several subsystems, and it needs to be integrated for its use for IPC cross-net messages. Mainly: 

- __Client-side__: It needs to be integrated in the cross-msg subsystem to resolve bottom-up messages from checkpoints. 
- __Service-side__: An IPC-specific BitswapStore able to inspect the state of a subnet through the IPC agent to resolve Bitswap requests for cross-net messages needs to be implemented.

**Comment by aakoshh** [comment]
As Alfonso said, the IPLD Resolver is more general than originally envisaged in that it is content agnostic, it operates on the level of CIDs, without knowledge of what they are for, and it is recursive, if the data structure is recursive as well. This means that in theory the a peer can ask for the root CID of the state tree and get everything under it transferred to them. 

If you want to restrict the content to the checkpoints, and your data structures are recursive (e.g. an AMT), then I think what you'd need to do is decide how far back you are willing to serve checkpoints for (e.g. after 24 hours the data should have been replicated on the parent and can be distributed through its own blocks), read those checkpoints into the agent's storage, or at least index the CIDs they contain. Then, when a request comes, you can reject it if it's not part of the CIDs you anticipated you had to serve.
